"""
Audit-ready, self-contained HTML reports (open in browser -> Ctrl/Cmd+P -> PDF).
Directly serves the brief's "auto-generating compliance evidence packages for audits".
"""
from __future__ import annotations

import html
from datetime import date

from .agents import maintenance_rca, compliance_report

_CSS = """
<style>
 * { font-family: -apple-system, Segoe UI, Roboto, sans-serif; }
 body { color:#1a1f26; margin:40px; max-width:900px; }
 h1 { font-size:22px; margin:0 0 4px; }
 h2 { font-size:15px; margin:26px 0 8px; border-bottom:2px solid #ff6b35; padding-bottom:4px; color:#b8431a; }
 .sub { color:#666; font-size:13px; margin-bottom:20px; }
 .badge { display:inline-block; padding:3px 10px; border-radius:5px; font-size:12px; font-weight:700; }
 .Healthy,.Covered { background:#e6f4ea; color:#1e7a34; }
 .Watch { background:#fdf3d8; color:#8a6d1a; }
 .At,.Gap { background:#fde8e8; color:#c0362c; }
 table { width:100%; border-collapse:collapse; font-size:13px; margin:8px 0; }
 th { text-align:left; background:#f3f4f6; padding:8px; border:1px solid #dde; }
 td { padding:8px; border:1px solid #dde; vertical-align:top; }
 .kpi { display:inline-block; border:1px solid #dde; border-radius:8px; padding:10px 16px; margin:4px 8px 4px 0; }
 .kpi b { font-size:22px; display:block; }
 .foot { margin-top:30px; color:#999; font-size:11px; border-top:1px solid #eee; padding-top:8px; }
 ul { line-height:1.6; }
</style>
"""


def _wrap(title: str, body: str) -> str:
    return (f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(title)}</title>"
            f"{_CSS}</head><body>{body}"
            f"<div class='foot'>Generated by Industrial Knowledge Intelligence — Unified Asset "
            f"&amp; Operations Brain · {date.today().isoformat()}</div></body></html>")


def rca_report_html(engine, equipment_id: str) -> str:
    d = maintenance_rca(engine, equipment_id)
    hc = "Healthy" if d["health_label"].startswith("Healthy") else "Watch" if d["health_label"].startswith("Watch") else "At"
    rows = "".join(
        f"<tr><td>{html.escape(t['date'])}</td><td>{html.escape(t['doc_id'])}</td>"
        f"<td>{html.escape(t['doc_type'])}</td><td>{html.escape(t.get('summary',''))}</td></tr>"
        for t in d["timeline"])
    rcs = "".join(f"<li>{html.escape(r['text'])} <b>[{html.escape(r['doc_id'])}]</b></li>" for r in d["root_causes"])
    recs = "".join(f"<li>{html.escape(r['text'])} <b>[{html.escape(r['doc_id'])}]</b></li>" for r in d["recommendations"])
    themes = ", ".join(html.escape(t) for t in d["recurring_themes"]) or "none"

    body = f"""
    <h1>Root Cause Analysis Report — {html.escape(d['equipment'])}</h1>
    <div class='sub'>Maintenance Intelligence &amp; RCA Agent</div>
    <div>
      <span class='kpi'>Health<b><span class='badge {hc}'>{html.escape(d['health_label'])}</span></b></span>
      <span class='kpi'>Score<b>{d['health_score']}/100</b></span>
      <span class='kpi'>Failure events<b>{d['n_failure_events']}</b></span>
      <span class='kpi'>Peak vibration<b>{d['peak_vibration_mm_s'] or '—'}{' mm/s' if d['peak_vibration_mm_s'] else ''}</b></span>
    </div>
    <h2>Recurring failure themes (systemic signal)</h2><p>{themes}</p>
    <h2>Root Cause Analysis</h2><p>{html.escape(d['narrative'])}</p>
    <h2>Failure &amp; inspection timeline</h2>
    <table><tr><th>Date</th><th>Document</th><th>Type</th><th>Summary</th></tr>{rows}</table>
    <h2>Documented root causes</h2><ul>{rcs or '<li>None recorded.</li>'}</ul>
    <h2>Predictive maintenance recommendations</h2><ul>{recs or '<li>None recorded.</li>'}</ul>
    <h2>Evidence documents</h2><p>{', '.join(html.escape(x) for x in d['linked_documents']) or 'none'}</p>
    """
    return _wrap(f"RCA — {d['equipment']}", body)


def compliance_pack_html(engine) -> str:
    d = compliance_report(engine)
    s = d["summary"]
    rows = "".join(
        f"<tr><td><span class='badge {r['status']}'>{r['status']}</span></td>"
        f"<td>{html.escape(r['regulation'])}</td><td>{html.escape(r['area'])}</td>"
        f"<td>{html.escape(r['requirement'])}</td>"
        f"<td>{', '.join(html.escape(e) for e in r['evidence']) or '—'}</td></tr>"
        for r in d["requirements"])
    gaps = "".join(f"<li><b>{html.escape(g['regulation'])}</b> — {html.escape(g['requirement'])}</li>"
                   for g in d["gap_list"])
    body = f"""
    <h1>Regulatory Compliance Evidence Package</h1>
    <div class='sub'>Quality &amp; Regulatory Compliance Intelligence · OISD · Factory Act · PESO</div>
    <div>
      <span class='kpi'>Coverage<b>{s['coverage_pct']}%</b></span>
      <span class='kpi'>Requirements<b>{s['total_requirements']}</b></span>
      <span class='kpi'>Covered<b>{s['covered']}</b></span>
      <span class='kpi'>Gaps<b>{s['gaps']}</b></span>
    </div>
    <h2>Open compliance gaps — corrective action required</h2>
    <ul>{gaps or '<li>No gaps — full coverage.</li>'}</ul>
    <h2>Requirement coverage matrix</h2>
    <table><tr><th>Status</th><th>Regulation</th><th>Area</th><th>Requirement</th><th>Evidence</th></tr>{rows}</table>
    """
    return _wrap("Compliance Evidence Package", body)
